version: '3.8'

services:
  # Base de Datos Relacional
  postgres_db:
    image: postgres:latest
    container_name: backend_course_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: MyStoreDb
    ports:
      - "5432:5432"      
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - store-network

  # Caché
  redis_cache:
    image: redis:latest
    container_name: backend_course_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data      
    networks:
      - store-network

  # Bus de Mensajes
  rabbitmq_bus:
    image: rabbitmq:3-management
    container_name: backend_course_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest    
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - store-network
    
  # Motor de Búsqueda y Logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data 
    networks:
      - store-network

  # Visualizador
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENCRYPTIONKEY="c149666f827448839076829741285324"
      - XPACK_REPORTING_ENCRYPTIONKEY="83917462058372649103847562910384"
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="92038475610293847561029384756102"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - store-network      

# DEFINICIÓN GLOBAL DE REDES Y VOLÚMENES
networks:
  store-network:
    driver: bridge

volumes:
  postgres_data:      
  redis_data:
  rabbit_data:
  elastic_data: # <--- Nombre consistente con el mapeo de arriba
    driver: local