version: '3.8'

services:
  store.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=MyStoreDb;Username=admin;Password=password123
      - MassTransit__Host=rabbitmq_bus
    ports:
      - "8080:8080"
    networks:
      - store-network

  store.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MassTransit__Host=rabbitmq_bus
    networks:
      - store-network